// Display-sized copies; original project artwork remains available.
export const previewImages:Record<string,string> = {
  "/assets/projects/bad-apple-strava.webp": "/assets/previews/bad-apple-strava.webp",
  "/assets/projects/bad-apple-sleep.webp": "/assets/previews/bad-apple-sleep.webp",
  "/assets/projects/bad-apple-kitkat.webp": "/assets/previews/bad-apple-kitkat.webp",
  "/assets/projects/vim-vim-revolution.webp": "/assets/previews/vim-vim-revolution.webp",
  "/assets/projects/bad-apple-pretext.webp": "/assets/previews/bad-apple-pretext.webp",
  "/assets/projects/smart-glasses-laser-tag.webp": "/assets/previews/smart-glasses-laser-tag.webp",
  "/assets/projects/viewlingo.webp": "/assets/previews/viewlingo.webp",
  "/assets/projects/smart-glasses-sheet-music.webp": "/assets/previews/smart-glasses-sheet-music.webp",
  "/assets/projects/poke-rogue-biomes.webp": "/assets/previews/poke-rogue-biomes.webp",
  "/assets/projects/bad-apple-pdf.webp": "/assets/previews/bad-apple-pdf.webp",
  "/assets/projects/engineering-physics-all-at-once.webp": "/assets/previews/engineering-physics-all-at-once.webp",
  "/assets/projects/pixel-brush.webp": "/assets/previews/pixel-brush.webp",
  "/assets/projects/ultrasonic-holography.webp": "/assets/previews/ultrasonic-holography.webp",
  "/assets/projects/bad-apple-but-it-s-3blue1brown.webp": "/assets/previews/bad-apple-but-it-s-3blue1brown.webp",
  "/assets/projects/bad-apple-irl.webp": "/assets/previews/bad-apple-irl.webp",
  "/assets/projects/ubc-aerodesign.webp": "/assets/previews/ubc-aerodesign.webp",
  "/assets/projects/ubc-rover.webp": "/assets/previews/ubc-rover.webp",
  "/assets/projects/stemformulas.webp": "/assets/previews/stemformulas.webp",
  "/assets/projects/the-fizz-buzz.webp": "/assets/previews/the-fizz-buzz.webp",
  "/assets/projects/b-flat.webp": "/assets/previews/b-flat.webp",
  "/assets/projects/desynthesia.webp": "/assets/previews/desynthesia.webp",
  "/assets/projects/title-sequences.webp": "/assets/previews/title-sequences.webp",
  "/assets/projects/northernlion-edits.webp": "/assets/previews/northernlion-edits.webp",
  "/assets/projects/league-of-legends-avatar.webp": "/assets/previews/league-of-legends-avatar.webp",
  "/assets/projects/vancouver-canucks-anime-intro.webp": "/assets/previews/vancouver-canucks-anime-intro.webp",
  "/assets/projects/iskaarly.webp": "/assets/previews/iskaarly.webp",
  "/assets/projects/league-of-legends-marvel.webp": "/assets/previews/league-of-legends-marvel.webp",
  "/assets/projects/league-of-legends-infinity-war.webp": "/assets/previews/league-of-legends-infinity-war.webp"
};
